name: increment-cargo-version

on:
  workflow_dispatch:

jobs:
  check_compilation:
    name: Increment cargo version
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      # - name: Modify file
      #   shell: bash
      #   run: |
      #     echo "Running git status"
      #     echo "another line\n" >> myfile
      #     git status
      # - name: Stage
      #   run: git add .
      # - name: Commit
      #   run: git commit -m "Add line to myfile"
      # - name: Push
      #   run: git push origin HEAD:main
      # - name: Open PR
      #   uses: actions/github-script@v6
      #   id: pr
      #   with:
      #     script: |
      #       const { repo, owner } = context.repo;
      #       const result = await github.rest.pulls.create({
      #         title: 'Update myfile',
      #         owner,
      #         repo,
      #         head: '${{ github.ref_name }}',
      #         base: 'main',
      #         body: 'Just updating myfile'
      #       });
      #       github.rest.issues.addLabels({
      #         labels: ['automerge']
      #       });
      - name: event_path
        run: cat ${{ github.event_path }}
